
# Configure Logging
logging:
  level:
    root: INFO
    com.toomuch2learn: DEBUG
    org.springframework: INFO
    org.apache.catalina: ERROR

# Configure Spring specific properties
spring:

  # Enable/Disable hot swapping
  devtools:
    restart:
      enabled: true
      log-condition-evaluation-delta: false
  # Datasource Configurations
  h2:
    console:
      enabled: true
      path: /h2

  # R2DBC Configuration
  r2dbc:
    url: r2dbc:h2:mem:///cataloguedb3
    username: sa
    password:
    initialization-mode: always