logging.level:
  com.com.se.sample.dao: TRACE
server:
  port: 8000
elasticsearch:
  password: 31323334
  user: elastic
  hosts:
    - http://localhost:9200
    - ${ELASTIC_ADDRESS:http://localhost}:${ELASTIC_PORT:9200}
  connectTimeout: 10000
  connectionRequestTimeout: 10000
  socketTimeout: 10000
  maxRetryTimeoutMillis: 60000

index:
  book: book
  product: product
