#spring:
#  cloud:
#    function:
#      definition: consumer;producer
#    stream:
#      kafka:
#        binder:
#          brokers: localhost:9092
#
#      bindings:
#        producer-out-0:
#          destination: first-topic
#  consumer-in-0:
#    destination: first-topic

spring:
  cloud:
    function:
      definition: consumer;producer
    stream:
      kafka:
        bindings:
          producer-out-0:
            producer:
              configuration:
                value.serializer: com.example.communication.dto.coverters.MessageSerializer
          consumer-in-0:
            consumer:
              configuration:
                value.deserializer: com.example.communication.dto.coverters.MessageDeSerializer
        binder:
          brokers: localhost:9092

      bindings:
        producer-out-0:
          destination: first-topic
          producer:
            useNativeEncoding: true # Enables using the custom serializer
        consumer-in-0:
          destination: first-topic
          consumer:
            use-native-decoding: true # Enables using the custom deserializer
